name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Checkout code
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build client
        run: docker build -t joshcausey/client ./client
      
      - name: Push client to Docker Hub
        run: docker push joshcausey/client