name: Build and push to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to Docker Hub
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build client
        run: docker build -t joshcausey/multi-client:${GITHUB_SHA} ./client

      - name: Build server
        run: docker build -t joshcausey/multi-server:${GITHUB_SHA} ./worker

      - name: Build worker
        run: docker build -t joshcausey/multi-worker:${GITHUB_SHA} ./worker
      
      - name: Push imaages to Docker Hub
        run: |
          docker push joshcausey/multi-client:${GITHUB_SHA}ß
          docker push joshcausey/multi-server:${GITHUB_SHA}
          docker push joshcausey/multi-worker:${GITHUB_SHA}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Update kubectl
        run: gcloud components update kubectl