name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to Docker Hub
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build client
        run: docker build -t joshcausey/multi-client ./client

      - name: Build server
        run: docker build -t joshcausey/multi-server ./worker

      - name: Build worker
        run: docker build -t joshcausey/multi-worker ./worker
      
      - name: Push imaages to Docker Hub
        run: |
          docker push joshcausey/multi-client
          docker push joshcausey/multi-server
          docker push joshcausey/multi-worker